// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/ads": {
    params: {};
  };
  "/pending-submissions": {
    params: {};
  };
  "/reconciliation": {
    params: {};
  };
  "/submit-ad": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/ads" | "/pending-submissions" | "/reconciliation" | "/submit-ad" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./ads/page.jsx": {
    id: "ads/page";
    page: "/ads";
  };
  "./pending-submissions/page.jsx": {
    id: "pending-submissions/page";
    page: "/pending-submissions";
  };
  "./reconciliation/page.jsx": {
    id: "reconciliation/page";
    page: "/reconciliation";
  };
  "./submit-ad/page.jsx": {
    id: "submit-ad/page";
    page: "/submit-ad";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "ads/page": typeof import("./src/app/./ads/page.jsx");
  "pending-submissions/page": typeof import("./src/app/./pending-submissions/page.jsx");
  "reconciliation/page": typeof import("./src/app/./reconciliation/page.jsx");
  "submit-ad/page": typeof import("./src/app/./submit-ad/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};