// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/reset-password": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/account/verify-advertiser": {
    params: {};
  };
  "/ads": {
    params: {};
  };
  "/pending-submissions": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/reconciliation": {
    params: {};
  };
  "/submit-ad": {
    params: {};
  };
  "/submit-ad/success": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/reset-password" | "/account/signin" | "/account/signup" | "/account/verify-advertiser" | "/ads" | "/pending-submissions" | "/privacy" | "/reconciliation" | "/submit-ad" | "/submit-ad/success" | "/terms" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/reset-password/page.jsx": {
    id: "account/reset-password/page";
    page: "/account/reset-password";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./account/verify-advertiser/page.jsx": {
    id: "account/verify-advertiser/page";
    page: "/account/verify-advertiser";
  };
  "./ads/page.jsx": {
    id: "ads/page";
    page: "/ads";
  };
  "./pending-submissions/page.jsx": {
    id: "pending-submissions/page";
    page: "/pending-submissions";
  };
  "./privacy/page.jsx": {
    id: "privacy/page";
    page: "/privacy";
  };
  "./reconciliation/page.jsx": {
    id: "reconciliation/page";
    page: "/reconciliation";
  };
  "./submit-ad/page.jsx": {
    id: "submit-ad/page";
    page: "/submit-ad";
  };
  "./submit-ad/success/page.jsx": {
    id: "submit-ad/success/page";
    page: "/submit-ad/success";
  };
  "./terms/page.jsx": {
    id: "terms/page";
    page: "/terms";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/reset-password/page": typeof import("./src/app/./account/reset-password/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "account/verify-advertiser/page": typeof import("./src/app/./account/verify-advertiser/page.jsx");
  "ads/page": typeof import("./src/app/./ads/page.jsx");
  "pending-submissions/page": typeof import("./src/app/./pending-submissions/page.jsx");
  "privacy/page": typeof import("./src/app/./privacy/page.jsx");
  "reconciliation/page": typeof import("./src/app/./reconciliation/page.jsx");
  "submit-ad/page": typeof import("./src/app/./submit-ad/page.jsx");
  "submit-ad/success/page": typeof import("./src/app/./submit-ad/success/page.jsx");
  "terms/page": typeof import("./src/app/./terms/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};